[build]
  functions = "netlify/functions"
  publish = "public"  # If you have static files

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-auth-token"
    
[blobs]
  stores = ["vertexHubData"]
