[build]
  # Disable automatic page build if no publish directory is needed
  publish = ""  # Empty if no static site; set to "public" if you have pages
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# Define build contexts to separate concerns
[context.production]
  command = "echo 'Deploying functions only' && cd netlify/functions && npm install"  # Install deps in functions dir
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "echo 'Deploying functions only' && cd netlify/functions && npm install"

# Ensure functions are not skipped
[functions]
  ignored_build = false

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-auth-token"

# Enable Netlify Blobs
[blobs]
  stores = ["vertexHubData"]
